# Generated by Django 6.0.1 on 2026-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=10)),
                ('status', models.CharField(choices=[('unwatched', 'Unwatched'), ('watched', 'Watched')], default='unwatched', max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
